### ISSUE TITLE
Where do diagram renders come from?

### ISSUE THREAD

**Issue by ColonelPanicks** [alces-software/overware#55]
It doesn't look like the rendering of switch maps comes from inventoryware templates. What in overware is determining this? 

In the event that a different asset type has a map it cannot be rendering due to the map rendering stuff being handled elsewhere!

**Comment by DavidMarchant** [comment]
What template is rendered is determined by the concatenation of the inventoryware's config file `etc/templates.yml` and all of your plugins' `etc/templates.yml` config files. Overware uses the format `diagram-markdown` so to, for instance, have a rack also display its map like a switch you would need
```
diagram-markdown:
  default: server.md.erb
  server: server.md.erb
  switch: diagram-switch.md.erb
  rack: diagram-switch.md.erb
```
somewhere in your config files
Alternatively, if you wanted the default to be rendering like a switch:
```
diagram-markdown:
  default: diagram-switch.md.erb
  server: server.md.erb
  switch: diagram-switch.md.erb
 ```
These are both reliant on having a `diagram-switch.md.erb` template ofc
